#Things that just won't change, man
illegals = ('\\','//',':','*','?','"','<','>','|')

elementNames = {
    0:"Air",
    1:"Sand",
    2:"Stone",
    3:"Water",
    4:"Sugar",
    5:"Wall",
    6:"Dirt",
    7:"Mud",
    8:"Plant",
    9:"Lava",
    10:"Wet Sand",
    11:"Gravel",
    12:"Obsidian",
    13:"Steam",
    14:"Glass",
    15:"Sugar Water",
    16:"Cloud",
    17:"Brick",
    18:"Algae",
    19:"Glass Shards",
    20:"The Sun",
    21:"The Moon",
    22:"Snow",
    23:"Ice",
    24:"Sugar Crystals",
    25:"Packed Ice",
    26:"Life Particle",
    27:"Sludge",
    28:"Flower Seed",
    29:"Oil",
    30:"Fire",
    31:"Wood",
    32:"Ash",
    33:"Cloner",
    34:"Clay",
    35:"Void",
    36:"Petal",
    37:"Cancer Particle",
    38:"Iron",
    39:"Iron Sand",
    40:"Iron Brick",
    41:"Smart Remover",
    42:"Smart Converter",
    43:"Electricity",
    44:"Rustish Iron",
    45:"Rust",
    46:"Salt",
    47:"Salt Water",
    48:"Salt Crystal",
    49:"Leaf",
    50:"Jammer",
    51:"Antisand",
    52:"Antistone",
    53:"Antiwater",
    54:"Identity Crisis",
    55:"Molten Salt",
    56:"Smoke",
    57:"Virus",
    58:"Gold",
    59:"Covered Wire",
    60:"Strange Matter",
    61:"Shockwave",
    62:"Sapling",
    63:"Broken Brick",
    64:"Acid Cloud",
    65:"Acid",
    66:"Acid Sludge",
    67:"Explosion",
    68:"TNT",
    69:"C4",
    70:"Nuke",
    71:"Holy Water",
    72:"Dead Plant",
    73:"Coal",
    74:"Natural Gas",
    75:"Polluted Water",
    76:"Greenhouse Sun"
}



crashSplash = (
        "OH F### THIS WASN'T SUPPOSED TO HAPPEN!\nGOODBYE CRUEL WORLD!!!",
        "That's not very healthy!",
        "Well, you tried!",
        "Try using a graph next time.",
        "The sandbox didn't say it's sandboxing time.",
        "Your rot has brained.",
        "DEATH AND DESTRUCTION!!!!",
        "Oh good heavens!",
        "Oh e-gods! My sandbox is ruined!",
        "Why??????????????????????????????????????",
        "HOW?! I DID EVERYTHING RIGHT!",
        "Oh well.",
        "Poo"
    )

yeses = ("y","yes","yeah","do it","sure","alright","ok","ig","i guess","yay","pull the lever, cronk!","alrighty then","whatever","heck yes","hell yes","probably","ye","yea","yeah!","oh yes","i don't see why not","i dont see why not","the opposite of no","yep","yes sir","yessir","please do","do","1","i'd love to","i'd love to try it out","let's see what you've got","let's-a go!","lets a go","let's a go","lets a go!","mushroom kingdom here we come","may","smash","yeah, sure","yesure","let's kick bubblegum","activate","throttle","upgrade","proceed","bb","shure","surry boi","surry","yes please","yes maam","yes hoobaab")
noes = ("n","no","nah","nay","nein","it's opposite day","don't you dare","poop","do not","do not the cat","perish","hell no","heck no","probably not","jumpscare","no!","no!!","no!!!","mmm...","how could you screw it up this badly?","the opposite of yes","nope","not even close","please don't","don't","0","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","unrun","kill","oh no","ho ho ho ho no","steamed hams","nada","nay","pass","t_t","i'm sick rn","not today","chewing bubblegum","deactivate","turn back","i said turn back","snowgrave","die","di","noooooooooo","b","lmao nah","nada","zilch","q","no please","no thank you","no thanks")